menu:
  首页: { id: index, url: / }
  归档: { id: archives, url: /archives }
  标签: { id: tags, url: /tags }
  分类: { id: categories, url: /categories }
  关于: { id: about, url: /about }

github: luicfer

background-root: /images/background/
background: [ 1.png, 2.jpg ]

avatar: /images/ikaros.jpg

#### Comment
duoshuo:
  short_name: lucifer1029    ## duoshuo short name.